import pytest
import numpy as np
from ase import Atoms
from AtomWorldBench.atom_world.motif_detectors.cluster import ClusterDetector
from AtomWorldBench.tests.test_motif_detectors.common_detector_test import BaseMotifDetectorTest